[project]
name = "your project name"
version = "0.1.0"
description = "rpy2"
authors = ["Zhang Yingtan <bay237580157@outlook.com>"]
channels = ["conda-forge", "https://prefix.dev/r-forge/"]
platforms = ['win-64', 'osx-64']

[tasks]

[dependencies]
r-base = "4.1.*"
radian = ">=0.6.12,<0.7" # Visual Studio Code
r-languageserver = ">=0.3.15,<0.4" # Visual Studio Code
# r-httpgd = ">=1.3.1,<1.4" # Visual Studio Code
jupyterlab = ">=4.2.3" # JupyterLab
pixi-kernel = ">=0.3.0" # JupyterLab
r-irkernel = ">=1.3.2" # JupyterLab
python = "3.9.*"
pandas = ">=2.3.0,<3"
tqdm = ">=4.67.1,<5"
scikit-learn = ">=1.6.1,<2"
matplotlib = ">=3.9.4,<4"
seaborn = ">=0.13.2,<0.14"
rpy2 = ">=3.5.11,<4"
ipython = ">=8.18.1,<9"
r-installr = ">=0.23.4,<0.24"
r-matrix = ">=1.5_4.1,<2"
r-rcpparmadillo = ">=0.12.4.0.0,<0.13"
r-glasso = ">=1.11,<2"
r-irlba = ">=2.3.5.1,<3"
r-mass = ">=7.3_58.3,<8"


[target.osx-64.tasks]
code = "open -a \"Visual Studio Code\" ."

[activation.env]
PIXI_R_LIBS = "$CONDA_PREFIX/lib/R/library"
R_LIBS_USER = "$PIXI_R_LIBS"
R_LIBS = "$PIXI_R_LIBS"
R_DEFAULT_PACKAGES = ""
